// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbiwmbpfgcforgolqeri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiaXdtYnBmZ2Nmb3Jnb2xxZXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzE1MjksImV4cCI6MjA3MjUwNzUyOX0.-xkPPhLrVzVuasETn5sKX_6VUk_WYRSHJh87qNyKVlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});